from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "check_attribution"
PINNED_COMMIT = "a20028b98294b9cc8770f2015a92eb342224b788"


def run_check(root: Path = ROOT) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--check", "--root", str(root)],
        text=True,
        capture_output=True,
        check=False,
    )


def write(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def valid_translated_source() -> str:
    return f"""// Source note: Translated from PyQtGraph pyqtgraph/widgets/PlotWidget.py
// PyQtGraph ref: pyqtgraph-0.14.0
// Pinned commit: {PINNED_COMMIT}
// License: MIT; see THIRD_PARTY_NOTICES.md
int translated_symbol() {{ return 0; }}
"""


def documented_translated_source() -> str:
    return f"""// Source note: translated from PyQtGraph pyqtgraph/widgets/PlotWidget.py
// PyQtGraph ref: pyqtgraph-0.14.0
// Pinned commit: {PINNED_COMMIT}
// License: MIT; see THIRD_PARTY_NOTICES.md
int translated_symbol() {{ return 0; }}
"""


def translated_source_without_upstream_path(note_line: str) -> str:
    return f"""{note_line}
// PyQtGraph ref: pyqtgraph-0.14.0
// Pinned commit: {PINNED_COMMIT}
// License: MIT; see THIRD_PARTY_NOTICES.md
int translated_symbol() {{ return 0; }}
"""


def test_project_license_is_mit() -> None:
    text = (ROOT / "LICENSE").read_text(encoding="utf-8")
    assert "MIT License" in text
    assert "Permission is hereby granted" in text
    assert "pyqtgraph_to_cpp contributors" in text


def test_third_party_notices_cover_required_dependencies() -> None:
    text = (ROOT / "THIRD_PARTY_NOTICES.md").read_text(encoding="utf-8")
    for needle in (
        "PyQtGraph",
        "https://github.com/pyqtgraph/pyqtgraph",
        "License: MIT",
        "pyqtgraph-0.14.0",
        PINNED_COMMIT,
        "Qt",
        "LGPL",
        "GPL",
        "commercial",
        "OpenCV",
        "Apache-2.0",
        "Tests and benchmarks",
        "Project-authored tests and benchmarks are under the project MIT License",
        "No third-party source is vendored by this issue",
    ):
        assert needle in text


def test_third_party_notices_preserve_upstream_pyqtgraph_mit_notice() -> None:
    text = (ROOT / "THIRD_PARTY_NOTICES.md").read_text(encoding="utf-8")
    for needle in (
        "Copyright (c) 2012 University of North Carolina at Chapel Hill",
        "Luke Campagnola",
        "The MIT License",
        "Permission is hereby granted, free of charge",
        "The above copyright notice and this permission notice shall be included",
        "THE SOFTWARE IS PROVIDED \"AS IS\"",
    ):
        assert needle in text


def test_workflow_documents_license_and_attribution_policy() -> None:
    text = (ROOT / "docs" / "pyqtgraph-cpp-port-workflow.md").read_text(
        encoding="utf-8"
    )
    for needle in (
        "License and attribution policy",
        "Source note: translated/adapted from PyQtGraph <upstream-path>",
        "PyQtGraph ref: pyqtgraph-0.14.0",
        f"Pinned commit: {PINNED_COMMIT}",
        "License: MIT; see THIRD_PARTY_NOTICES.md",
        "Generated by <tool/script>",
        "Inputs: <source manifest/upstream path>",
        "Do not edit manually",
        "Original implementation; no PyQtGraph source translation",
    ):
        assert needle in text


def test_check_attribution_script_exists_with_shebang() -> None:
    text = SCRIPT.read_text(encoding="utf-8")
    assert text.startswith("#!/usr/bin/env python3")
    assert os.access(SCRIPT, os.X_OK)


def test_check_attribution_passes_on_repository() -> None:
    result = run_check()
    assert result.returncode == 0, result.stderr
    assert "Attribution audit passed" in result.stdout
    assert result.stderr == ""


def test_translated_cpp_without_source_note_fails(tmp_path: Path) -> None:
    write(
        tmp_path / "include" / "pyqtgraph" / "PlotWidget.cpp",
        "int missing_note() { return 0; }\n",
    )

    result = run_check(tmp_path)

    assert result.returncode != 0
    assert "include/pyqtgraph/PlotWidget.cpp" in result.stderr
    assert "missing source attribution note" in result.stderr
    assert len(result.stderr.strip().splitlines()) == 1


def test_translated_cpp_with_valid_source_note_passes(tmp_path: Path) -> None:
    write(
        tmp_path / "include" / "pyqtgraph" / "PlotWidget.cpp", valid_translated_source()
    )

    result = run_check(tmp_path)

    assert result.returncode == 0, result.stderr
    assert "Attribution audit passed" in result.stdout


def test_documented_source_note_form_passes(tmp_path: Path) -> None:
    write(
        tmp_path / "include" / "pyqtgraph" / "PlotWidget.cpp",
        documented_translated_source(),
    )

    result = run_check(tmp_path)

    assert result.returncode == 0, result.stderr
    assert "Attribution audit passed" in result.stdout


def test_multiline_c_block_source_note_passes(tmp_path: Path) -> None:
    write(
        tmp_path / "include" / "pyqtgraph" / "BlockComment.cpp",
        f"""/*
Source note: translated from PyQtGraph pyqtgraph/widgets/PlotWidget.py
PyQtGraph ref: pyqtgraph-0.14.0
Pinned commit: {PINNED_COMMIT}
License: MIT; see THIRD_PARTY_NOTICES.md
*/
int translated_symbol() {{ return 0; }}
""",
    )

    result = run_check(tmp_path)

    assert result.returncode == 0, result.stderr
    assert "Attribution audit passed" in result.stdout


def test_multiline_python_docstring_source_note_passes(tmp_path: Path) -> None:
    write(
        tmp_path / "src" / "pyqtgraph" / "plot_widget.py",
        f'''"""
Source note: translated from PyQtGraph pyqtgraph/widgets/PlotWidget.py
PyQtGraph ref: pyqtgraph-0.14.0
Pinned commit: {PINNED_COMMIT}
License: MIT; see THIRD_PARTY_NOTICES.md
"""

def translated_symbol() -> int:
    return 0
''',
    )

    result = run_check(tmp_path)

    assert result.returncode == 0, result.stderr
    assert "Attribution audit passed" in result.stdout


def test_source_note_without_upstream_path_after_pyqtgraph_fails(
    tmp_path: Path,
) -> None:
    write(
        tmp_path / "include" / "pyqtgraph" / "LineComment.cpp",
        translated_source_without_upstream_path(
            "// Source note: translated from PyQtGraph"
        ),
    )
    write(
        tmp_path / "include" / "pyqtgraph" / "BlockComment.cpp",
        translated_source_without_upstream_path(
            "/* Source note: translated from PyQtGraph */"
        ),
    )

    result = run_check(tmp_path)

    assert result.returncode != 0
    assert "include/pyqtgraph/LineComment.cpp: missing upstream path" in result.stderr
    assert "include/pyqtgraph/BlockComment.cpp: missing upstream path" in result.stderr


def test_generated_source_without_generation_inputs_fails(tmp_path: Path) -> None:
    write(
        tmp_path / "src" / "pyqtgraph" / "generated.cpp",
        "// Generated by scripts/generate_manifest\n"
        "// Do not edit manually\n"
        "int generated_symbol() { return 0; }\n",
    )

    result = run_check(tmp_path)

    assert result.returncode != 0
    assert "src/pyqtgraph/generated.cpp" in result.stderr
    assert "missing generation inputs" in result.stderr


def test_generated_source_with_source_field_still_requires_inputs(
    tmp_path: Path,
) -> None:
    write(
        tmp_path / "src" / "pyqtgraph" / "generated.cpp",
        "// Generated by scripts/generate_manifest\n"
        "// Source: port_manifest.yaml\n"
        "// Do not edit manually\n"
        "int generated_symbol() { return 0; }\n",
    )

    result = run_check(tmp_path)

    assert result.returncode != 0
    assert "src/pyqtgraph/generated.cpp" in result.stderr
    assert "missing generation inputs" in result.stderr


def test_generated_source_without_manual_edit_notice_fails(tmp_path: Path) -> None:
    write(
        tmp_path / "src" / "pyqtgraph" / "generated.cpp",
        "// Generated by scripts/generate_manifest\n"
        "// Inputs: port_manifest.yaml\n"
        "int generated_symbol() { return 0; }\n",
    )

    result = run_check(tmp_path)

    assert result.returncode != 0
    assert "src/pyqtgraph/generated.cpp" in result.stderr
    assert "missing manual edit notice" in result.stderr


def test_gitkeep_placeholders_are_ignored(tmp_path: Path) -> None:
    write(tmp_path / "include" / "pyqtgraph" / ".gitkeep", "")

    result = run_check(tmp_path)

    assert result.returncode == 0, result.stderr


def test_unrelated_tests_are_not_forced_to_have_notes(tmp_path: Path) -> None:
    write(tmp_path / "tests" / "test_smoke.py", "def test_smoke():\n    assert True\n")

    result = run_check(tmp_path)

    assert result.returncode == 0, result.stderr
